local TowersUHave = {}
for i,v in next, game:GetService("ReplicatedStorage").RemoteFunction:InvokeServer("Session", "Search", "Inventory.Troops") do
    if v.Equipped then
        table.insert(TowersUHave, i)
    end
end
wait(1)
local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/bloodball/-back-ups-for-libs/main/kav"))()
local Window = Library.CreateLib("VTDS HUB", "King翻译家")
local Credits = Window:NewTab("其他人")
local Lobby = Window:NewTab("比赛")
local AutoChain = Lobby:NewSection("自动能力")
local turn = false
local CreditsBar = Credits:NewSection("信息")
CreditsBar:NewLabel("King汉化支持了")
CreditsBar:NewLabel("bianhquan12345/bianhquan12345#7794: 所有者脚本")
CreditsBar:NewLabel("vinhkhang100/Khang#3082: 其他人")



local Stack = Lobby:NewSection("堆")
Stack:NewTextBox("这里是塔名", "确保你站在你想放的位置", function(txt)
	local args = {
		[1] = "Troops",
		[2] = "Place",
		[3] = txt,
		[4] = {
			["Rotation"] = CFrame.new(0,5,0,0,5,0,0,5,0,0,5,0),
			["Position"] = game.Players.LocalPlayer.character.HumanoidRootPart.Position - Vector3.new(0,5,0)
		}
	}

	game:GetService("ReplicatedStorage").RemoteFunction:InvokeServer(unpack(args))
end)
local Lobbyl = Window:NewTab("大厅")
local LeaderBoard = Lobbyl:NewSection("大厅")

LeaderBoard:NewButton("更新排行榜", "这将更新排行榜", function()

	local A_1 = "Leaderboard"
	local A_2 = "Request"
	local Event = game:GetService("ReplicatedStorage").RemoteFunction
	Event:InvokeServer(A_1, A_2)

end)
local Selling = Lobby:NewSection("Selling")
Selling:NewButton("出售所有塔", "好的", function()
	for index,value in pairs(game.Workspace.Towers:GetChildren()) do
		-- Script generated by R2Sv2
		-- R2Sv2 developed by Luckyxero

		local A_1 = "Troops"
		local A_2 = "Sell"
		local A_3 = 
			{
				["Troop"] = value 
			}
		local Event = game:GetService("ReplicatedStorage").RemoteFunction
		Event:InvokeServer(A_1, A_2, A_3)

	end
	wait()
end)


Selling:NewTextBox("出售所有塔名称", "好的", function(txt)
	for index,value in pairs(game.Workspace.Towers:GetChildren()) do
		if value.Replicator:GetAttribute("Type") == txt then



			local A_1 = "Troops"
			local A_2 = "Sell"
			local A_3 = 
				{
					["Troop"] = value 
				}
			local Event = game:GetService("ReplicatedStorage").RemoteFunction
			Event:InvokeServer(A_1, A_2, A_3)
		end
		wait()
	end


end)
Stack:NewButton("放置奇怪的王牌飞行员", "这仅适用于某些地图", function()
	local A_1 = "Troops"
	local A_2 = "Place"
	local A_3 = "Ace Pilot"
	local A_4 = 
		{
			["Rotation"] = CFrame.new(0,5,0,0,0,0,0,0,0,0,-90,-90),
			["Position"] = game.Players.LocalPlayer.character.HumanoidRootPart.Position - Vector3.new(0,5,0)
		}
	local Event = game:GetService("ReplicatedStorage").RemoteFunction
	Event:InvokeServer(A_1, A_2, A_3, A_4)
end)

Stack:NewButton("放置奇怪的追求", "和王牌飞行员一样", function()
	local A_1 = "Troops"
	local A_2 = "Place"
	local A_3 = "Pursuit"
	local A_4 = 
		{
			["Rotation"] = CFrame.new(0,5,0,0,0,0,0,0,0,0,-90,-90), 
			["Position"] = game.Players.LocalPlayer.character.HumanoidRootPart.Position - Vector3.new(0,5,0)
		}
	local Event = game:GetService("ReplicatedStorage").RemoteFunction
	Event:InvokeServer(A_1, A_2, A_3, A_4)
end)
Stack:NewButton("放置奇怪的王牌飞行员2", "我想是为了休息，哈哈", function()
	local A_1 = "Troops"
	local A_2 = "Place"
	local A_3 = "Ace Pilot"
	local A_4 = 
		{
			["Rotation"] = CFrame.new(0,5,0,0,0,90,-90), 
			["Position"] = game.Players.LocalPlayer.character.HumanoidRootPart.Position - Vector3.new(0,5,0)
		}
	local Event = game:GetService("ReplicatedStorage").RemoteFunction
	Event:InvokeServer(A_1, A_2, A_3, A_4)
end)
Stack:NewButton("放置奇怪的追求2", "我想是为了休息，哈哈", function()
	local A_1 = "Troops"
	local A_2 = "Place"
	local A_3 = "Pursuit"
	local A_4 = 
		{
			["Rotation"] = CFrame.new(0,5,0,0,0,90,-90), 
			["Position"] = game.Players.LocalPlayer.character.HumanoidRootPart.Position - Vector3.new(0,5,0)
		}
	local Event = game:GetService("ReplicatedStorage").RemoteFunction
	Event:InvokeServer(A_1, A_2, A_3, A_4)
end)
local Check = 0 local Skipping = Lobby:NewSection("Skipping") Skipping:NewKeybind("SkipKey", "Breh", Enum.KeyCode.F, function() local args = { [1] = "Waves", [2] = "Skip" }

game:GetService("ReplicatedStorage").RemoteFunction:InvokeServer(unpack(args)) end) local CheckEd = false

local lolc = false

AutoChain:NewButton("自动链", "确保你有至少3个lv 2以上的指挥官", function()

while true do
for index,value in pairs(game.Workspace.Towers:GetChildren()) do if value.Owner.Value == game.Players.LocalPlayer and value.Replicator:GetAttribute("Type") == "Commander" then local args = { [1] = "Troops", [2] = "Abilities", [3] = "Activate", [4] = { ["Name"] = "Call Of Arms", ["Troop"] = value } }

					game:GetService("ReplicatedStorage").RemoteFunction:InvokeServer(unpack(args))
					wait(10.1)
			 end
			 end

end

   end)
Stack:NewDropdown("斯塔克大厦", "堆叠塔名称的替代", TowersUHave, function(currentOption)
    local A_1 = "Troops"
		local A_2 = "Place"
		local A_3 = currentOption
		local A_4 = 
			{
				["Rotation"] = CFrame.new(0,5,0), 
				["Position"] = game.Players.LocalPlayer.character.HumanoidRootPart.Position - Vector3.new(0,5,0)
			}
		local Event = game:GetService("ReplicatedStorage").RemoteFunction
		Event:InvokeServer(A_1, A_2, A_3, A_4)
end)
local CopyDiscordServerLink = Credits:NewSection("复制不和谐的服务器链接")
CopyDiscordServerLink:NewButton("复制", "为什么你连这个都不明白？", function()
    setclipboard("https://discord.gg/yEBheZxfN7")
end)
local ok = game.Players.LocalPlayer.PlayerGui.GameGui.Health.Wave
Selling:NewButton("出售所有农场", "breh？？固态硬盘", function()
local wo = game.Workspace.Towers:GetChildren()
for i,v in pairs(wo) do
if v.Owner.Value == game.Players.LocalPlayer and v.Replicator:GetAttribute("Type") == "Farm" then
		local A_1 = "Troops"
			local A_2 = "Sell"
			local A_3 = 
				{
					["Troop"] = v
				}
			local Event = game:GetService("ReplicatedStorage").RemoteFunction
			Event:InvokeServer(A_1, A_2, A_3)
		
		wait()
	
end
end
end)
local DmCheck = false

AutoChain:NewToggle("垃圾邮件医疗能力", "Breh", function(state)
    if state then
        DmCheck = true
    else
        DmCheck = false
    end
end)
while wait(1) do
if DmCheck == true then
local args = {
    [1] = "Troops",
    [2] = "Place",
    [3] = "Medic",
    [4] = {
        ["Rotation"] = CFrame.new(Vector3.new(0, 0, 0), Vector3.new(-0, -0, -1)),
        ["Position"] = game.Players.LocalPlayer.character.HumanoidRootPart.Position - Vector3.new(0,5,0)
    }
}
local Dmagain = game.Workspace.Towers:GetChildren()
game:GetService("ReplicatedStorage").RemoteFunction:InvokeServer(unpack(args))
for i,v in pairs(Dmagain) do
if v.Owner.Value == game.Players.LocalPlayer and v.Replicator:GetAttribute("Type") == "Medic" then
local args = {
    [1] = "Troops",
    [2] = "Upgrade",
    [3] = "Set",
    [4] = {
        ["Troop"] = v
    }
}

game:GetService("ReplicatedStorage").RemoteFunction:InvokeServer(unpack(args))
local args = {
    [1] = "Troops",
    [2] = "Upgrade",
    [3] = "Set",
    [4] = {
        ["Troop"] = v
    }
}

game:GetService("ReplicatedStorage").RemoteFunction:InvokeServer(unpack(args))
local args = {
    [1] = "Troops",
    [2] = "Upgrade",
    [3] = "Set",
    [4] = {
        ["Troop"] = v
    }
}

game:GetService("ReplicatedStorage").RemoteFunction:InvokeServer(unpack(args))
local args = {
    [1] = "Troops",
    [2] = "Upgrade",
    [3] = "Set",
    [4] = {
        ["Troop"] = v
    }
}

game:GetService("ReplicatedStorage").RemoteFunction:InvokeServer(unpack(args))
local args = {
    [1] = "Troops",
    [2] = "Upgrade",
    [3] = "Set",
    [4] = {
        ["Troop"] = v
    }
}

game:GetService("ReplicatedStorage").RemoteFunction:InvokeServer(unpack(args))
wait(0.5)
local args = {
    [1] = "Troops",
    [2] = "Abilities",
    [3] = "Activate",
    [4] = {
        ["Name"] = "Cleansing",
        ["Troop"] = v
    }
}

game:GetService("ReplicatedStorage").RemoteFunction:InvokeServer(unpack(args))
wait(0.1)
local args = {
    [1] = "Troops",
    [2] = "Sell",
    [3] = {
        ["Troop"] = v
    }
}

game:GetService("ReplicatedStorage").RemoteFunction:InvokeServer(unpack(args))
end
end
end
end

LeaderBoard:NewButton("ButtonText", "ButtonInfo", function()
    print("Clicked")
end)